### ISSUE TITLE
H20 Smart TV Box (RK3228A Rockchip device)

### ISSUE THREAD

**Issue by KarimosDz** [llbranco/PPPwn_STvBox#1]
Does it work on this device?
![S352d10c2c1284b21af37bd9c037e157cH](https://github.com/llbranco/PPPwn_STvBox/assets/147206256/dc77fa9f-c125-4c16-b38a-2d4d61fc973e)

**Comment by llbranco** [comment]
the processor is rockchip (RK3228A), it's not supported **YET**
but I have plans to port to most (if not all) Tv Boxes

**Comment by FaLL3N-ighT** [comment]
We were waiting with great interest [llbranco](https://github.com/llbranco) ..thanks for your work !

**Comment by llbranco** [comment]
should be fixed on the new version
